import fs from 'node:fs';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const files=['assets/js/identity-import-wizard-entry.js','assets/js/update-center-live-debug.js','assets/js/bootstrap.js','service-worker.js'];
for(const file of files){assert.equal(fs.existsSync(file),true,`missing:${file}`);const result=spawnSync(process.execPath,['--check',file],{encoding:'utf8'});assert.equal(result.status,0,`syntax:${file}:${result.stderr}`);}
const wizard=fs.readFileSync(files[0],'utf8'),live=fs.readFileSync(files[1],'utf8'),bootstrap=fs.readFileSync(files[2],'utf8'),worker=fs.readFileSync(files[3],'utf8');
for(const token of ['duplicateOnly','renderDuplicateLite','attachEssentialBatches','scheduleOptionalWorkbench','review-render-completed','optional-workbench-started','optional-workbench-completed'])assert.match(wizard,new RegExp(token));
assert.ok(wizard.indexOf("emit('review-render-completed'")<wizard.indexOf('scheduleOptionalWorkbench(renderGeneration)'),'terminal completion must precede optional workbench');
assert.doesNotMatch(wizard,/\['review_workbench',attachReviewWorkbench\]/);
assert.match(live,/LIVE_DEBUG_SCHEMA='pokemon-sleep-update-center-live-debug\/1\.1'/);
assert.match(live,/optional-workbench-failed/);
assert.match(live,/REDACT_KEY/);
assert.match(live,/image_bytes/);
assert.match(live,/image_base64/);
assert.match(live,/ocr_full_text/);
assert.match(live,/SAFE_COUNT_KEY/);
assert.match(live,/image_count/);
assert.match(bootstrap,/APP_VERSION = 'v0\.3\.63'/);
assert.match(bootstrap,/20260803-g13-2e-finalize-nonblocking-workbench/);
assert.match(worker,/pokemon-sleep-ai-v0\.3\.63-g13-2e-finalize-nonblocking-workbench/);
console.log(JSON.stringify({ok:true,gate:'G13.2E finalize nonblocking workbench',version:'v0.3.63'}));
