import assert from 'node:assert/strict';
import fs from 'node:fs';

const bootstrap=fs.readFileSync('assets/js/bootstrap.js','utf8');
const worker=fs.readFileSync('service-worker.js','utf8');
const index=fs.readFileSync('index.html','utf8');

const versionMatch=bootstrap.match(/const APP_VERSION = '(v\d+\.\d+\.\d+)'/);
const buildMatch=bootstrap.match(/const VERSION = '([^']+)'/);
const workerVersionMatch=worker.match(/const APP_VERSION = '(v\d+\.\d+\.\d+)'/);
const workerBuildMatch=worker.match(/const APP_BUILD = '([^']+)'/);
assert.ok(versionMatch,'bootstrap active version missing');
assert.ok(buildMatch,'bootstrap active build missing');
assert.ok(workerVersionMatch,'worker active version missing');
assert.ok(workerBuildMatch,'worker active build missing');
const activeVersion=versionMatch[1];
const activeBuild=buildMatch[1];
assert.equal(workerVersionMatch[1],activeVersion,'worker version constant must match bootstrap authority');
assert.equal(workerBuildMatch[1],activeBuild,'worker build constant must match bootstrap authority');
assert.match(bootstrap,/version_authority_repaired/);
assert.match(bootstrap,/MutationObserver/);
assert.match(bootstrap,/unified-import-analysis-workbench\.js/);
assert.ok(worker.includes(`pokemon-sleep-ai-${activeVersion}-${activeBuild.replace(/^\d{8}-/,'')}`),'worker cache must match bootstrap authority');
assert.match(worker,/app_version\s*:\s*APP_VERSION/,'worker activation must use the single version constant');
assert.match(worker,/build\s*:\s*APP_BUILD/,'worker activation must use the single build constant');
assert.match(worker,/pokemon-sleep-version-activated/);
assert.match(worker,/cache:'no-store'/);
assert.match(worker,/keys\.filter\(\(key\)=>key!==CACHE\)|keys\.filter\(\(key\) => key !== CACHE\)/);
assert.ok(index.includes(`bootstrap.js?v=${activeBuild}`),'index bootstrap build must equal active authority build');
assert.match(activeVersion,/^v\d+\.\d+\.\d+$/,'active version must use three-part semver');
console.log(JSON.stringify({ok:true,gate:`${activeVersion} version authority`,downgrade_guard:true,cache_rotated:true,three_part_version:true,single_worker_constants:true}));
