import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const authoritySource=fs.readFileSync('assets/js/version-authority.js','utf8');
const bootstrap=fs.readFileSync('assets/js/bootstrap.js','utf8');
const worker=fs.readFileSync('service-worker.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const sandbox={};sandbox.globalThis=sandbox;vm.runInNewContext(authoritySource,sandbox,{filename:'version-authority.js'});
const authority=sandbox.PokemonSleepVersionAuthority;
assert.ok(authority,'central version authority missing');
const activeVersion=authority.app_version;
const activeBuild=authority.app_build;
assert.match(activeVersion,/^v\d+\.\d+\.\d+(?:\.\d+)?$/,'active version must use supported semver or hotfix semver');
assert.ok(activeBuild&&activeBuild!==activeVersion,'active build missing or invalid');
assert.equal(authority.cache_name,`pokemon-sleep-ai-${activeVersion}-${activeBuild.replace(/^\d{8}-/,'')}`,'cache must derive from central authority');
assert.match(bootstrap,/version-authority\.js/,'bootstrap must import central authority');
assert.match(bootstrap,/authority\.app_version/,'bootstrap must consume central app version');
assert.match(bootstrap,/authority\.app_build/,'bootstrap must consume central build');
assert.match(bootstrap,/version_authority_repaired/);
assert.match(bootstrap,/MutationObserver/);
assert.match(bootstrap,/unified-import-analysis-workbench\.js/);
assert.match(worker,/importScripts\('\.\/assets\/js\/version-authority\.js'\)/,'worker must import central authority');
assert.match(worker,/cache_name:CACHE/,'worker cache must consume central authority');
assert.match(worker,/app_version:APP_VERSION/,'worker activation must use central version alias');
assert.match(worker,/build:APP_BUILD/,'worker activation must use central build alias');
assert.match(worker,/pokemon-sleep-version-activated/);
assert.match(worker,/cache:'no-store'/);
assert.match(worker,/keys\.filter\(\s*\(?key\)?\s*=>\s*key\s*!==\s*CACHE\s*\)/,'worker must delete caches other than active CACHE; formatting is not authority');
assert.ok(index.includes('bootstrap.js'),'index must load bootstrap');
assert.doesNotMatch(index,/bootstrap\.js\?v=v?\d+\.\d+\.\d+(?:\.\d+)?/,'index must not use semantic version literals as cache tokens');
console.log(JSON.stringify({ok:true,gate:`${activeVersion} central version authority`,downgrade_guard:true,cache_rotated:true,hotfix_semver_supported:true,single_authority_file:true}));
