import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const rescue=read('assets/js/v0389-rescue-catalog-import.js');
const db=read('assets/js/database.js');
const legacySnapshot=read('assets/js/v0382-image-byte-snapshot.js');
const authority=read('assets/js/v0382-release-authority.js');
const bootstrap=read('assets/js/bootstrap.js');
const sw=read('service-worker.js');
const index=read('index.html');
assert.match(rescue,/pokemon_sleep_rescue_import_staging/);
assert.match(rescue,/尚未載入/);
assert.match(rescue,/PokemonSleepPublicRecipeRegistry/);
assert.match(rescue,/requestForcedDatabaseLoad\(\);location\.reload\(\)/);
assert.match(rescue,/import\('\.\/importer\.js'\)/);
assert.match(rescue,/if\(preview\.conflict_count\)/);
assert.match(rescue,/await stagePut\(payload\)/);
assert.match(rescue,/JSON 僅解析、驗證及暫存，不修改玩家資料/);
assert.match(db,/pokemon-sleep-force-database-load-once/);
assert.match(db,/sessionStorage\.removeItem\(FORCE_LOAD_KEY\)/);
assert.doesNotMatch(legacySnapshot,/MutationObserver/);
assert.doesNotMatch(legacySnapshot,/service-worker-v0382/);
assert.doesNotMatch(legacySnapshot,/dataset\.appVersion/);
assert.match(authority,/v0\.3\.(?:89|90|91|92|93)/);
assert.match(authority,/service-worker\.js/);
assert.match(authority,/detail\.rescue\|\|detail\.readonly/);
assert.match(bootstrap,/v0\.3\.(?:89|90|91|92|93)/);
assert.match(bootstrap,/v0389-rescue-catalog-import\.js/);
assert.match(sw,/v0\.3\.(?:89|90|91|92|93)/);
assert.match(sw,/v0389-rescue-catalog-import\.js/);
assert.match(index,/2026080[56]-v03(?:89-rescue-catalog-import-recovery|90-worker-isolated-legacy-sqlite-load|91-worker-lifecycle-race-closure|92-new-user-database-bootstrap-freeze|93-post-migration-startup-isolation)/);
console.log('v0.3.89+ rescue catalog/import transition contract PASS');
