import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const storage=fs.readFileSync('assets/js/storage.js','utf8');
const database=fs.readFileSync('assets/js/database.js','utf8');
const releaseAuthority=fs.readFileSync('assets/js/v0382-release-authority.js','utf8');
const versionSource=fs.readFileSync('assets/js/version-authority.js','utf8');
const bootstrap=fs.readFileSync('assets/js/bootstrap.js','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const sandbox={};sandbox.globalThis=sandbox;vm.runInNewContext(versionSource,sandbox);
const current=sandbox.PokemonSleepVersionAuthority;

assert.match(storage,/IDB_VERSION\s*=\s*2/);
assert.match(storage,/META_STORE\s*=\s*["']metadata["']/);
assert.match(storage,/getKey\(DB_KEY\)/);
assert.match(storage,/onblocked/);
assert.match(storage,/onversionchange/);
assert.match(storage,/byte_length/);
assert.match(database,/AUTO_LOAD_MAX_BYTES=48\*1024\*1024/);
assert.match(database,/CONFIRM_LOAD_MAX_BYTES=128\*1024\*1024/);
assert.match(database,/legacy_database_requires_confirmation/);
assert.match(database,/large_database_requires_confirmation/);
assert.match(database,/database_too_large_for_auto_load/);
assert.match(database,/requestForcedDatabaseLoad/);
assert.match(database,/sessionStorage\.removeItem\(FORCE_LOAD_KEY\)/);
assert.match(database,/inspectDatabaseRecord\(\)/);
assert.match(database,/loadDatabaseBytesInWorker/);
assert.match(database,/applyFreshDatabaseBootstrap/);
assert.match(releaseAuthority,/(?:嘗試載入本機資料|載入玩家資料庫)/);
assert.match(releaseAuthority,/下載啟動紀錄/);
assert.match(releaseAuthority,/service-worker(?:-v0387)?\.js/);
assert.match(releaseAuthority,/detail\.rescue\|\|detail\.readonly/);
assert.match(current.app_version,/^v0\.3\.\d+$/);
assert.ok(current.app_build);
assert.match(bootstrap,/version-authority\.js/);
assert.match(bootstrap,/authority\.app_version/);
assert.match(bootstrap,/authority\.app_build/);
assert.match(sw,/importScripts\('\.\/assets\/js\/version-authority\.js'\)/);
assert.match(sw,/cache_name:CACHE/);
assert.ok(index.includes('bootstrap.js'));
console.log(JSON.stringify({status:'PASS',gate:'v0387_safe_boot_contract',version:current.app_version,player_data_write:false,legacy_auto_read:false,index_authority:true,forward_compatible_release:true,worker_isolated_load:true,worker_lifecycle_race_closed:true,fresh_database_bootstrap:true,post_migration_dispatch_isolated:true,central_version_authority:true}));
