import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const rescue=read('assets/js/v0389-rescue-catalog-import.js');
const itemMaster=read('assets/js/public-item-master.js');
const db=read('assets/js/database.js');
const legacySnapshot=read('assets/js/v0382-image-byte-snapshot.js');
const authority=read('assets/js/v0382-release-authority.js');
const versionAuthority=read('assets/js/version-authority.js');
const bootstrap=read('assets/js/bootstrap.js');
const sw=read('service-worker.js');
const index=read('index.html');
assert.match(rescue,/pokemon_sleep_rescue_import_staging/);
assert.match(rescue,/尚未載入/);
assert.match(rescue,/PokemonSleepPublicRecipeRegistry/);
assert.match(rescue,/requestForcedDatabaseLoad\(\);location\.reload\(\)/);
assert.match(rescue,/import\('\.\/importer\.js'\)/);
assert.match(rescue,/if\(preview\.conflict_count\)/);
assert.match(rescue,/await stagePut\(payload\)/);
assert.match(rescue,/JSON 僅解析、驗證及暫存，不修改玩家資料/);
assert.match(rescue,/import \{PUBLIC_ITEM_MASTER\} from '\.\/public-item-master\.js'/);
assert.doesNotMatch(rescue,/const ITEM_EFFECTS=/);
assert.match(itemMaster,/export const PUBLIC_ITEM_MASTER_VERSION=/);
assert.match(itemMaster,/export const PUBLIC_ITEM_MASTER=/);
assert.match(itemMaster,/effect_description_zh_tw/);
assert.match(db,/pokemon-sleep-force-database-load-once/);
assert.match(db,/sessionStorage\.removeItem\(FORCE_LOAD_KEY\)/);
assert.doesNotMatch(legacySnapshot,/MutationObserver/);
assert.doesNotMatch(legacySnapshot,/service-worker-v0382/);
assert.doesNotMatch(legacySnapshot,/dataset\.appVersion/);
assert.match(authority,/version-authority\.js/);
assert.match(authority,/authority\.app_version/);
assert.match(authority,/service-worker\.js/);
assert.match(authority,/detail\.rescue\|\|detail\.readonly/);
assert.match(bootstrap,/v0389-rescue-catalog-import\.js/);
assert.match(sw,/v0389-rescue-catalog-import\.js/);
assert.match(sw,/public-item-master\.js/);
const sandbox={globalThis:{}};vm.runInNewContext(versionAuthority,sandbox);
const current=sandbox.globalThis.PokemonSleepVersionAuthority;
assert.match(current.app_version,/^v\d+(?:\.\d+){2,}$/);
assert.match(current.app_build,/^\d{8}-[a-z0-9-]+$/);
assert.equal(current.cache_name,`pokemon-sleep-ai-${current.app_version}-${current.app_build.replace(/^\d{8}-/,'')}`);
assert.match(index,/src="\.\/assets\/js\/bootstrap\.js"/);
assert.doesNotMatch(index,/bootstrap\.js\?v=/);
console.log(`rescue catalog/import shared-authority contract PASS (${current.app_version})`);